---
# tasks file for netplan-dns

- name: Configure network interface
  become: true
  template:
    src: tmp.j2
    dest: "/etc/netplan/{{ item.interface }}.yaml"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ interfaces }}"
  notify:
    - apply network interface
#    - restart networkd
#    - restart resolved

#- name: Apply network interface configuration
#  become: true
#  shell: netplan apply
